apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: grafana-{{ .Values.role }}-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: grafana-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: grafana
    role: {{ .Values.role }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
          {{- if include "ingressversion" . | eq "networking.k8s.io/v1" }}
          service:
            name: grafana-{{ $.Values.role }}
            port:
              number: {{ required ".ports.grafana is required" $.Values.ports.grafana }}
          {{- else }}
          serviceName: grafana-{{ $.Values.role }}
          servicePort: {{ required ".ports.grafana is required" $.Values.ports.grafana }}
          {{- end }}
        path: /
        pathType: Prefix
  {{- end }}
